name: PR Review with Progress Tracking

# Example workflow that uses the reusable PR review workflow
# This demonstrates the default comprehensive review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  comprehensive-review:
    name: Comprehensive PR Review
    uses: ./core-action.yml
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        